Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/12/2019
tipo
   tpessoa=registro
      nome,nacionalidade,sexo:caractere
      idade,peso:inteiro
      altura:real
   fimregistro
Var
   // Seção de Declarações das variáveis


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...


Fimalgoritmo