Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/11/2019
Var
// Seção de Declarações das variáveis 
num1,num2,resultado:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um número: ")
leia(num1)
escreva("Digite outro número: ")
leia(num2)
resultado:=num1+num2
escreva("A soma é = ",resultado)
Fimalgoritmo