Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/11/2019
Var
// Seção de Declarações das variáveis 
f,c:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o valor da temperatura em graus Celsius: ")
leia(c)
f:=(9*c+160)/5
escreva("A temperatura em Farenheit é: ",f)
Fimalgoritmo