Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/11/2019
Var
   // Seção de Declarações das variáveis
   f,c:real
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite o valor da temperatura em graus Farenheit: ")
   leia(f)
   c:=(f-32)*(5/9)
   escreva("A temperatura em Celsius é: ",c)
Fimalgoritmo