Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/11/2019
Var
   // Seção de Declarações das variáveis
   vk,vm:real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite a velocidade em Km/h: ")
   leia(vk)
   vm:=vk/3.6
   escreva("Velocidade em m/s: ",vm)
Fimalgoritmo