Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/12/2019
Var
   // Seção de Declarações das variáveis
   sb,sl,desc:real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Informe o salário bruto: ")
   leia(sb)
   desc:=(sb-0.1*sb)
   sl:=(desc-0.05*desc)
   escreva("O salário líquido é: ",sl)
Fimalgoritmo