Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/11/2019
Var
// Seção de Declarações das variáveis 
nome,sobrenome,nomeC:caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Insira o seu nome: ")
leia(nome)
escreva("Insira o seu sobrenome: ")
leia(sobrenome)
nomeC:=nome+" "+sobrenome;
escreva("Nome Completo: " ,nomeC)
Fimalgoritmo