Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/12/2019
Var
   // Seção de Declarações das variáveis
   numero,soma,c:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   c:=1
   soma:=0
   enquanto (c<=10) faca
      soma:=soma+c
      c:=c+1
   fimenquanto
   escreva("A Soma dos numeros de 1 ate 10 é: ",soma)
Fimalgoritmo