Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/12/2019
Var
   // Seção de Declarações das variáveis
   soma,i:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   soma:=0
   para i de 1 ate 100 passo 1 faca
      soma:=soma+i
   fimpara
   escreva("Soma dos números: ",soma)
Fimalgoritmo