Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/12/2019
Var
// Seção de Declarações das variáveis 
i:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Múltiplos de 7 inferiores a 1000")
para i de 7 ate 1000 passo 7 faca
escreval(i)
fimpara
Fimalgoritmo