Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/12/2019
Var
// Seção de Declarações das variáveis 
i:inteiro
res:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
res:=1
para i de 1 ate 15 passo 1 faca
res:=res*i
fimpara
escreva("O resultado dos produtos é: ",res)
Fimalgoritmo