Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/12/2019
Var
   // Seção de Declarações das variáveis
   i:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Número       Quadrado      Cubo")
   para i de 0 ate 10 passo 1 faca
      escreval("  ",i,"            ",i^2,"          ",i^3)
   fimpara
Fimalgoritmo