Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/10/2019
Var
   // Seção de Declarações das variáveis
   raio,area: real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Insira o raio da pizza: ")
   leia(raio)
   area <-pi*raio*raio
   escreva("A área da pizza: ")
   escreva(area:4:1)
Fimalgoritmo