Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/10/2019
Var
   // Seção de Declarações das variáveis
   preco,npreco: real
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite o preço do produto: ")
   leia(preco)
   npreco:=preco-0.1*preco
   escreva("O novo preço é: ",npreco)
Fimalgoritmo