Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/10/2019
Var
   // Seção de Declarações das variáveis
   peso,pesoGramas: real
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite o seu peso em kilos: ")
   leia(peso)
   pesoGramas:=peso*1000
   escreva("O seu peso em gramas é: ",pesoGramas," gramas.")
Fimalgoritmo