Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/10/2019
Var
   // Seção de Declarações das variáveis
   lado,area:real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite a medida do lado do quadrado: ")
   leia(lado)
   area:=lado*lado
   escreva("A área do quadrado é: ",area," unidade de área")
Fimalgoritmo