Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/12/2019
Var
   // Seção de Declarações das variáveis
   anos,dias:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite sua idade em anos: ")
   leia(anos)
   dias:=12*30*anos
   escreva("Sua idade corresponde a",dias," dias.")
Fimalgoritmo