Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/10/2019
Var
   // Seção de Declarações das variáveis
   a,b:logico

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite uma expressao lógica: ")
   leia(a)
   escreva("Digite outra expressao lógica: ")
   leia(b)
   escreva("O primeiro valor é:",a," o segundo é:",b)
Fimalgoritmo